version: '3'

services:
  redis:
    image: redis:alpine
    container_name: 'redis-queue'
    restart: always
    command: 'redis-server --requirepass docker'
    ports:
      - 4001:6379
    volumes:
      - './volume-data/redis-queue:/data'
